services:
  postgres:
    image: postgres:14
    container_name: postgress
    environment:
      POSTGRES_DB: slemaDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminadmin
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
